### ISSUE TITLE
Question about data splitting

### ISSUE THREAD

**Issue by kunkunlin1221** [zylbuaa/ECL#1]
Hi, authors. First, thank you for your good work.

I have problem to reproduce the original results, it seems that we need your training, validation, test dataset list because of the randomness of each computers is different. 

Could you provide your data list?

Thanks!

**Comment by zylbuaa** [comment]
Hi! Thank you for expressing interest in our work. I'm sorry for not getting back to you sooner. I have uploaded the data list and our model weights, you can directly test them on the datasets.
