### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yanjiusheng123456** [zylbuaa/ECL#2]

**Comment by zylbuaa** [comment]
你好，非常感谢你喜欢我的工作。model_path是模型存放的地址，训练时模型会保存在这个位置，你可以修改为自己的模型存储位置。







-----Original Messages-----
From:yanjiusheng123456 ***@***.***>
Send time:Monday, 03/25/2024 11:38:10
To: zylbuaa/ECL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zylbuaa/ECL] 怎么得到'the path of the model' (Issue #2)






你的工作做的非常棒，但我在复现你的工作的时候遇见了一个问题，我把数据集拆分出来了，就是不知道怎么获得the path of the model

parser.add_argument('--model_path', type=str, default="/media/disk/zyl/Experiment/ISIC_CL/ISIC2018/test_git/", help='the path of the model')
